# Generated by Django 3.2 on 2021-04-29 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія для  публікації', 'verbose_name_plural': 'Категорії  для  публікації'},
        ),
    ]
